### ISSUE TITLE
kmz to gpx: Does GPSBabel support KMZ?

### ISSUE THREAD

**Issue by GPSBabelDeveloper** [thanasisn/gpx_tools#1]
Does this really work?
https://github.com/thanasisn/gpx_tools/blob/9ebcefa80ee1d2dbb79d6c1401e26358d2f6ff0b/kmz_to_gpx.sh#L27
I don't think I ever committed KMZ support.  I don't see it in our public tree.

If the KMZ is relatively simple (no balloon contents that need rewritten to not use local paths, no icons on local systems, etc) it should be a "mere" matter of unzipping the kmz and taking the first lml that you find.

If you'd like to teach GPSBabel about KMZ, that would be great, too.

**Comment by thanasisn** [comment]
Haha you are absolutely right!!
This is a skeleton script that never worked, but I have forgot it along side with the working ones!

Now,I recall, that I have unzipped the kmz and got the data I wanted manual...
Excuse me, it have been 5 years since, I will convert it to a set of instructions as a reminder.

Thanks a lot for the notice!!!
